# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Zero
SEOTitle: Zero | Orange's Space

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Zero

description: Life without examination is not worth living
author:
  name: Orange Killer
  email: adaqueen2001@outlook.com
  github: ZeroAda
  # twitter: dbtek
  # pinterest: asd123
  # linkedin: asd123
  bio: Life without examination is not worth living
  email_md5: c7e9841794a0740cdcaee500ff805299

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate


# Friends
friends: [
    {
        title: "Zero",
        href: "https://ZeroAda.github.io/"
    }
    {
        title: "Qi",
        href: "https://www.cnblogs.com/keshuqi"
    }
]