baseURL: 'https://ZeroAda.github.io/'
title: Orange
paginate: 5
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: UA-123-45
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: Orange
  description: Chenyi Li's Blog
  keywords:
    - Blog
    - Chenyi
    - PaperMod
  author: Chenyi Li
  images:
    - '<link or path of image for opengraph, twitter-cards>'
  DateFormat: May 17th 2022
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    favicon: <link / abs url>
    favicon16x16: <link / abs url>
    favicon32x32: <link / abs url>
    apple_touch_icon: apple-touch-icon.png
    safari_pinned_tab: <link / abs url>
  label:
    text: Orange
    icon: apple-touch-icon.png
    iconHeight: 35
  profileMode:
    enabled: true
    title: Orange
    subtitle: Computer Engineering | Neuroscience
    imageUrl: portrait.JPG
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "Welcome to my blog. I am Kiwi \U0001F95D"
  socialIcons:
    - name: github
      url: 'https://github.com/ZeroAda/'
  analytics:
    google:
      SiteVerificationTag: XYZabc
    bing:
      SiteVerificationTag: XYZabc
    yandex:
      SiteVerificationTag: XYZabc
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  editPost:
    URL: 'https://github.com/<path_to_repo>/content'
    Text: Suggest Changes
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: Tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 40
